#------------------------------------------------------------------------------
# usage: Use tutor to enable the hastexo AWS S3 plugin
#------------------------------------------------------------------------------
name: Open edX Tutor k8s enable tutor-contrib-k8s-deploy-tasks plugin
description: Github Action to install and enable the Tutor plugin lpm0073/tutor-contrib-k8s-deploy-tasks
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  tutor-plugin-version:
    description: 'The version of tutor-ecommerce to install'
    required: false
    default: latest
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: install plugin
      id: install-plugin
      shell: bash
      run: pip install git+https://github.com/cookiecutter-openedx/tutor-contrib-k8s-deploy-tasks${{ inputs.tutor-plugin-version != 'latest' && format('@{0}', inputs.tutor-plugin-version) || '' }}

    - name: Enable plugin
      id: enable-plugin
      shell: bash
      run: tutor plugins enable k8s_deploy_tasks

    - name: Save config
      id: config-save
      shell: bash
      run: tutor config save
